feat: integrated with get-starknet-wallet
starkware-libs/starkgate-frontend pull request #163
Opened 2022-04-18 22:35 UTC by avimak

### Description of the Changes

Enhancement:
I've created a new library that is compatible with the current `getStarknet()` API but is able to support more wallets on StarkNet.
This PR integrates **starkgate-frontend** with that lib - adding multiple StarkNet wallets support in **starkgate-frontend** - without changing anything but one import line, and a few icons/texts to make the connect-L2-wallet step 100% wallet-agnostic.

### Checklist

- [x] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)  **-> not-applicable**
- [x] Test are passing in local environment
- [ ] Docs have been updated **-> non-required** 
- [x] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

2022-04-24 15:35 UTC, dan-ziv requested changes

2022-04-24 16:07 UTC, avimak commented on src/components/UI/WalletButton/WalletButton.js
> +          <img alt={''} height={logoSize} src={logoPath} width={logoSize} />
wallet window objects provide their own icon/logo data; here we show it via `<img>` element

2022-04-24 16:10 UTC, avimak commented on src/providers/WalletsProvider/WalletsProvider.js
>        setL2WalletConfig(walletConfig);
these 2 lines are called inside a `if enabled` clause -
```
      const wallet = getStarknet();
      const enabled = await wallet
        .enable(!autoConnect && {showModal: true})
        .then(address => !!address?.length);
      if (enabled) { // --> `enabled === true` means the wallet is successfully connected
        walletConfig.name = wallet.name || walletConfig.name;
        walletConfig.logoPath = wallet.icon || walletConfig.logoPath;
      }
```

2022-04-24 18:23 UTC, dan-ziv commented on src/providers/WalletsProvider/WalletsProvider.js
>        setL2WalletConfig(walletConfig);
```suggestion
      const wallet = getStarknet();
      const enabled = await wallet
        .enable(!autoConnect && {showModal: true})
        .then(address => !!address?.length);
      if (enabled) {
        walletConfig.name = wallet.name || walletConfig.name;
        walletConfig.logoPath = wallet.icon || walletConfig.logoPath;
        setL2WalletConfig(walletConfig);
        }
```

2022-04-25 09:44 UTC, dan-ziv commented on src/components/UI/WalletButton/WalletButton.js
> +          <img alt={''} height={logoSize} src={logoPath} width={logoSize} />
OK, can you please move this logic to a `renderWalletLogo` function so the JSX will be more readable?

2022-04-25 11:05 UTC, avimak commented on src/components/UI/WalletButton/WalletButton.js
> +          <img alt={''} height={logoSize} src={logoPath} width={logoSize} />
done :)

2022-04-25 11:22 UTC, dan-ziv approved these changes

2022-04-25 11:25 UTC, merged

2022-04-25 11:28 UTC, dan-ziv commented
:tada: This PR is included in version 1.3.0-dev.1 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkgate-frontend/releases/tag/v1.3.0-dev.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-02 16:03 UTC, dan-ziv commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkgate-frontend/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: