feat(3015991255): add to the functionality that close the modal if click on the blurry part
starkware-libs/starkgate-frontend pull request #259
Opened 2022-08-07 16:22 UTC by galuzan-starkware

### Description of the Changes

When the user will click on the blurry park of the modal then he will be back to the main screen

### Checklist

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

2022-08-08 14:39 UTC, dan-ziv requested changes

2022-08-08 14:39 UTC, dan-ziv commented on src/components/UI/Modal/Modal/Modal.js
> +  children,
Should be place last

2022-08-08 15:44 UTC, dan-ziv requested changes

2022-08-08 15:44 UTC, dan-ziv commented on src/components/UI/Modal/Modal/Modal.js
> +  children,
Again, children should be the last prop.
Second, don't pass the `hideModal` as a prop from outside, you can use the `ModalWrapper` to pass it (we're using `useHideModal` inside the  ModalWrapper)

2022-08-08 15:45 UTC, dan-ziv commented
@galuzan-starkware The description should describe the way of your solution and not what you already wrote in the title.

2022-08-08 15:46 UTC, dan-ziv commented
@galuzan-starkware Please check no bugs in Firefox.

2022-08-08 15:52 UTC, dan-ziv requested changes

2022-08-08 15:52 UTC, dan-ziv commented on src/components/UI/Modal/Modal/Modal.js
> +          onClick={() => exitable && hideModal()}
Export to named function (anonymous functions as event handlers are bad practice).

2022-08-08 15:52 UTC, dan-ziv commented on src/components/UI/Modal/Modal/Modal.js
> +            onClick={e => e.stopPropagation()}
Export to named function

2022-08-08 16:00 UTC, galuzan-starkware commented
> @galuzan-starkware The description should describe the way of your solution and not what you already wrote in the title.

done

2022-08-08 16:02 UTC, galuzan-starkware commented
> @galuzan-starkware Please check no bugs in Firefox.

There are no bugs relative to my changes, but I notice that if there is no MetaMask extension, then the app is crush

2022-08-10 08:00 UTC, dan-ziv approved these changes

2022-08-10 08:01 UTC, merged

2022-08-10 08:03 UTC, dan-ziv commented
:tada: This PR is included in version 1.8.0-dev.15 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkgate-frontend/releases/tag/v1.8.0-dev.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-15 14:02 UTC, dan-ziv commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkgate-frontend/releases/tag/v1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: