feat(3047139090): hide the available balance if wallet is not connected
starkware-libs/starkgate-frontend pull request #260
Opened 2022-08-08 08:44 UTC by galuzan-starkware

### Description of the Changes

The user now will not see the `<TokenBalance />` component unless he is logged in

### Checklist

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

2022-08-08 15:47 UTC, dan-ziv requested changes

2022-08-08 15:47 UTC, dan-ziv commented on src/components/Features/Transfer/Transfer.js
> +        isLoggedIn={isLoggedIn}
Don't pass it as a prop but use the hook inside the `NetworkMenu` itself.

2022-08-08 15:49 UTC, dan-ziv commented
@galuzan-starkware The description should describe the way of your solution and not what you already wrote in the title.

2022-08-10 06:12 UTC, galuzan-starkware commented
> @galuzan-starkware The description should describe the way of your solution and not what you already wrote in the title.

done

2022-08-10 06:51 UTC, dan-ziv approved these changes

2022-08-10 10:14 UTC, merged

2022-08-10 10:16 UTC, dan-ziv commented
:tada: This PR is included in version 1.8.0-dev.16 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkgate-frontend/releases/tag/v1.8.0-dev.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-15 14:02 UTC, dan-ziv commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkgate-frontend/releases/tag/v1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: